name: weather
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_places_flutter: 2.0.8
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  go_router: ^14.6.3
  dio: ^5.7.0
  gap: ^3.0.1
  intl: ^0.18.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  rive: ^0.13.20
  sign_in_button: ^3.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  open_weather_client: ^2.4.1
  one_clock: ^2.0.1
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  chat_gpt_sdk: ^3.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Change to your icon path
  adaptive_icon_background: "#ffffff" # Background color for Android adaptive icon

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/
