// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjayBllDSik_NYSNoxha5Rn7QAdKMV5Q',
    appId: '1:671979608570:web:c41b47b894aef08d492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    authDomain: 'fir-login-a8e63.firebaseapp.com',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
    measurementId: 'G-WJ2G2J2CBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ho3Qtl7c6SMObV5GVZSPmkxTiyhoODc',
    appId: '1:671979608570:android:ea971ca26c309bcd492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdNs5FIxG6_RKTPCjkG2AvPMLHyn85WcM',
    appId: '1:671979608570:ios:4945ab32c6c5c50e492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
    androidClientId: '671979608570-uqasgmqmsrk7ut917tf0497ocptrq49n.apps.googleusercontent.com',
    iosClientId: '671979608570-ohvaif0ar5mn0l5hvu91dmhl0il06pn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdNs5FIxG6_RKTPCjkG2AvPMLHyn85WcM',
    appId: '1:671979608570:ios:4945ab32c6c5c50e492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
    androidClientId: '671979608570-uqasgmqmsrk7ut917tf0497ocptrq49n.apps.googleusercontent.com',
    iosClientId: '671979608570-ohvaif0ar5mn0l5hvu91dmhl0il06pn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVjayBllDSik_NYSNoxha5Rn7QAdKMV5Q',
    appId: '1:671979608570:web:120cc8c35cd7ddc4492c43',
    messagingSenderId: '671979608570',
    projectId: 'fir-login-a8e63',
    authDomain: 'fir-login-a8e63.firebaseapp.com',
    databaseURL: 'https://fir-login-a8e63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a8e63.appspot.com',
    measurementId: 'G-6SHL9GZY0H',
  );
}
